jcommon/prometheus/pom.xml
jcommon/prometheus/prometheus-trace-etl/pom.xml
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/Metrics.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/MetricsManager.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/Prometheus.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/PrometheusCounter.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/PrometheusGauge.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/PrometheusHistogram.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/XmCounter.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/XmGauge.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/XmHistogram.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/binder/ClassLoaderMetricsReduced.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/binder/JvmGcMetricsReduced.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/binder/JvmMemoryMetricsReduced.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/binder/JvmThreadMetricsReduced.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/multi/MutiMetrics.java
jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/multi/MutiPrometheus.java

The "promethe-trace-etl" module provides the ability to create multiple Metrics instances and customize thread monitoring

add prometheus-trace-etl

---

hera-all/trace-etl/trace-etl-server/src/main/java/com/xiaomi/hera/trace/etl/consumer/MetricsParseService.java

transform MetricsParseService annotation

transform MetricsParseService annotation

---

jcommon/docean/src/main/java/com/xiaomi/youpin/docean/bo/Bean.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/bo/MvcConfig.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/common/DoceanConfig.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/common/Safe.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/config/HttpServerConfig.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/DoceanHttpServer.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/HttpRequestUtils.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/HttpResponseUtils.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/MvcContext.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/MvcRunnable.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/TextWebSocketHandler.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/upload/HttpUploadHandler.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/upload/Upload.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/util/ExceptionUtil.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/util/MethodFinder.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/plugin/IPlugin.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/AopTest.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/HttpServerTest.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/IocTest.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/demo/DemoController.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/ssl/HttpClient.java

(cherry picked from commit 6a3bf2b01dd85877de5c75aecd660becf7de839f)

translate docean

---

jcommon/nginx/src/main/java/com/xiaomi/youpin/nginx/NginxUtilsV2.java

update nginx, add health check

update nginx, add health check

---

jcommon/file/src/main/java/com/xiaomi/mone/file/LogFile2.java
jcommon/file/src/main/java/com/xiaomi/mone/file/ReadResult.java
jcommon/file/src/main/java/com/xiaomi/mone/file/common/FileInfoCache.java
jcommon/file/src/main/java/com/xiaomi/mone/file/common/FileUtils.java
jcommon/file/src/main/java/com/xiaomi/mone/file/listener/DefaultMonitorListener.java
jcommon/file/src/main/java/com/xiaomi/mone/file/listener/OzHeraReadListener.java
jcommon/file/src/main/java/com/xiaomi/mone/file/ozhera/HeraFileMonitor.java
jcommon/file/src/test/java/com/xiaomi/mone/file/FileMonitorUtilsTest.java
jcommon/file/src/test/java/com/xiaomi/mone/file/LogFileTest.java

update file montior

---

jcommon/file/src/main/java/com/xiaomi/mone/file/ozhera/HeraFileMonitor.java

If the monitored folder does not exist, create it.  (issue #747)

 If the monitored folder does not exist, create it.  (issue #747)

---

jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/demo/mydemo/DefaultDemoInterface.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/demo/mydemo/DemoCall.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/demo/mydemo/DemoInterface.java
jcommon/file/pom.xml
jcommon/file/src/main/java/com/xiaomi/mone/file/LogFile2.java
jcommon/file/src/main/java/com/xiaomi/mone/file/MLog.java
jcommon/file/src/main/java/com/xiaomi/mone/file/ReadListener.java
jcommon/file/src/main/java/com/xiaomi/mone/file/common/FileInfo.java
jcommon/file/src/main/java/com/xiaomi/mone/file/common/FileInfoCache.java
jcommon/file/src/main/java/com/xiaomi/mone/file/listener/DefaultMonitorListener.java
jcommon/file/src/main/java/com/xiaomi/mone/file/listener/OzHeraReadListener.java
jcommon/file/src/main/java/com/xiaomi/mone/file/ozhera/HeraFileMonitor.java
jcommon/pom.xml

refactor: file monitor update

---

jcommon/docean/pom.xml
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/Mvc.java
jcommon/pom.xml

fix mvc request method (#749)

---

jcommon/docean/src/main/java/com/xiaomi/youpin/docean/Mvc.java
jcommon/es/src/test/java/com/xiaomi/mone/es/test/EsClientTest.java
jcommon/excel/pom.xml
jcommon/feishu/pom.xml
jcommon/file/src/main/java/com/xiaomi/mone/file/MLog.java

feat: update dependency version and fix log bug

---

jcommon/docean/src/main/java/com/xiaomi/youpin/docean/Mvc.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/bo/MvcConfig.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/common/MvcConst.java

docean mvc add origin response path config

fea: add config for mvc origin_response path

---

jcommon/pom.xml
jcommon/sysFunc/pom.xml
jcommon/sysFunc/src/main/java/run/mone/sysFunc/SysFuncConst.java
jcommon/sysFunc/src/main/java/run/mone/sysFunc/SysFuncEnum.java
jcommon/sysFunc/src/main/java/run/mone/sysFunc/SysFuncUtils.java
jcommon/sysFunc/src/test/java/run/mone/sysFunc/test/SysFuncTest.java

add common func for mimeter

---

jcommon/mockjs/src/main/java/run/mone/mock/MockJsUtils.java
jcommon/mockjs/src/test/java/run/mone/mock/test/MockTest.java
jcommon/sysFunc/src/main/java/run/mone/sysFunc/SysFuncEnum.java

update  jcommon mockjs

---

jcommon/rpc-codes/pom.xml
jcommon/rpc-codes/src/main/java/com/xiaomi/data/push/uds/codes/DefaultHessian2FactoryInitializer.java
jcommon/rpc-codes/src/main/java/com/xiaomi/data/push/uds/codes/HessianCodes.java

add SerializerFactory when use hessian

add SerializerFactory when use hessian

---

jcommon/es/src/main/java/com/xiaomi/mone/es/EsClient.java
jcommon/es/src/test/java/com/xiaomi/mone/es/test/EsClientTest.java

#812
Improve the rate of ES write count under large data volume

feat: add init es sniffer

---

jcommon/docean-plugin/docean-plugin-mongodb/pom.xml
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/bo/User.java
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/controller/MongodbController.java
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/controller/UserController.java
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/mapper/UserMapper.java
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/service/UserService.java
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/vo/UserVo.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/Mvc.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/config/HttpServerConfig.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/HttpHandler.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/MvcResponse.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/MvcRunnable.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/TextWebSocketHandler.java
jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/context/WebSocketContext.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/HttpServerTest.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/demo/DemoController.java

Implement User Login and Logout Support in Doecean Framework with MongoDB (close #836)

Implement User Login and Logout Support in Doecean Framework with MongoDB (close #836)

---

jcommon/es/src/main/java/com/xiaomi/mone/es/EsClient.java
jcommon/es/src/test/java/com/xiaomi/mone/es/test/EsClientTest.java
jcommon/es/src/test/java/com/xiaomi/mone/es/test/EsProcessorClientTest.java
jcommon/file/src/main/java/com/xiaomi/mone/file/ILogFile.java
jcommon/file/src/main/java/com/xiaomi/mone/file/LogFile.java
jcommon/file/src/main/java/com/xiaomi/mone/file/LogFile2.java
jcommon/file/src/test/java/com/xiaomi/mone/file/LogFileTest.java

#847 
[Upgrade] Enhancements for File and Elasticsearch (ES) Modules

refactor: update es and upgrade file

---

jcommon/ai/bytedance/pom.xml
jcommon/ai/bytedance/src/main/java/run/mone/ai/bytedance/DoubaoClient.java
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/auth/AuthAop.java
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/bo/User.java
jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/service/MongoService.java
jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/HttpServerTest.java
jcommon/pom.xml

[enhancement] JCommon MongoDB supports pagination queries #851

[enhancement] JCommon MongoDB supports pagination queries #851

---

jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/auth/Auth.java

JCommon MongoDB fix default role for annotation

[enhancement] JCommon MongoDB fix default role for annotation

---

jcommon/codegen/pom.xml
jcommon/codegen/src/main/java/run/mone/ai/codegen/FeatureGenerator.java
jcommon/codegen/src/main/java/run/mone/ai/codegen/UnitTestGenerator.java
jcommon/codegen/src/main/java/run/mone/ai/codegen/bo/FeatureGeneratType.java
jcommon/codegen/src/main/java/run/mone/ai/codegen/bo/FeatureGenerateBo.java
jcommon/codegen/src/main/java/run/mone/ai/codegen/util/TemplateUtils.java
jcommon/codegen/src/main/resources/tlp/code_test.txt
jcommon/codegen/src/main/resources/tlp/controller.java
jcommon/codegen/src/main/resources/tlp/pojo.java
jcommon/codegen/src/main/resources/tlp/service.java
jcommon/codegen/src/main/resources/tlp/test.java
jcommon/codegen/src/main/resources/tlp/transfer.java
jcommon/codegen/src/main/resources/tlp/vo.java

feat(codegen): support feature and test and table generation based on template or generator

feat(codegen): support feature and test and table generation

---

jcommon/api/src/main/java/com/xiaomi/data/push/uds/processor/StreamCallback.java
jcommon/api/src/main/java/com/xiaomi/data/push/uds/processor/UdsProcessor.java
jcommon/pom.xml
jcommon/rcurve/README.md
jcommon/rcurve/pom.xml
jcommon/rcurve/src/main/java/com/xiaomi/data/push/common/NetUtils.java
jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsClient.java
jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/handler/ClientStreamCallback.java
jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/handler/MessageTypes.java
jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/handler/UdsClientHandler.java
jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/handler/UdsServerHandler.java
jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/processor/sever/MockStreamProcessor.java
jcommon/rcurve/src/test/java/com/xiaomi/mone/rcurve/test/UdsTest.java

feat: mesh streaming response support (#894)

feat: mesh streaming response support (#894)

---

jcommon/rcurve/src/main/java/com/xiaomi/data/push/common/NetUtils.java
jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsClient.java
jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsServer.java

chore: update NetUtils, UdsClient, and UdsServer

chore: update NetUtils, UdsClient, and UdsServer

---

jcommon/es/pom.xml
jcommon/es/src/main/java/com/xiaomi/mone/es/EsClient.java

- 删除了 EsClient 构造函数中的 validateParams 方法调用 -该方法似乎未在代码中定义，移除以修复潜在错误- 更新了项目版本号至1.6.3-jdk21

refactor(es): 移除 EsClient 中的参数验证

---

jcommon/mcp/mcp-feishu/pom.xml
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/FeishuApplication.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/config/McpStdioTransportConfig.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/function/FeishuDocFunction.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/model/BlockType.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/model/DocBlock.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/model/DocContent.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/model/DocPermission.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/model/Files.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/server/FeishuMcpServer.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/service/FeishuDocService.java
jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/util/FeishuHttpClient.java
jcommon/mcp/mcp-feishu/src/main/resources/application.properties
jcommon/mcp/mcp-feishu/src/test/java/run/mone/mcp/feishu/function/FeishuDocFunctionTest.java

- Add Feishu document base service (FeishuDocService)
- Implement core features for doc creation, editing and permission management
- Integrate with Feishu Open API for document operations
- Add unit tests to ensure functionality

feat(mcp-feishu): add lark document mcp util
