XiaoMi/mone

- gateway-manager/gateway-server/src/main/java/com/xiaomi/youpin/gwdash/controller/ApiGroupInfoController.java
- gateway-manager/gateway-server/src/main/java/com/xiaomi/youpin/gwdash/controller/FilterController.java
> gateway-manager

- jcommon/catPlugin/README.MD
> [docs] catPLUgin add note

- jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/classloader/ClassLoaderExecute.java
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/processor/client/CallMethodProcessor.java
支持了dubbo 在 sidecar模式下传递上线文 RpcContext
> [feat][jcommon-rcurve] Support dubbo context transfer in sidecar mode

- jcommon/hera/hera-trace/README.md
Add hera module comments in Chinese
> Add hera module comments in Chinese

- jcommon/file/src/test/java/com/xiaomi/mone/file/MLogTest.java
> log custom line pattern top test

- hera-all/hera-tspandata/.gitignore
- hera-all/hera-tspandata/pom.xml
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TAttributeKey.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TAttributeType.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TAttributes.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TEvent.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TExtra.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TInstrumentationLibraryInfo.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TKind.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TLink.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TResource.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TSpanContext.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TSpanData.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TStatus.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TTraceState.java
- hera-all/hera-tspandata/src/main/java/com/xiaomi/hera/tspandata/TValue.java
> Hera init add hera-tspandata

- jcommon/mongodb/src/main/java/com/xiaomi/data/push/mongodb/MongoDb.java
add annotation for mongoDb interface method
> add annotation

- hera-all/milog/log-common/src/main/java/com/xiaomi/mone/log/utils/ConfigUtils.java
support log-agent get nacos address from ENV
> support log-agent get nacos address from ENV

- jcommon/k8s/src/main/java/com/xiaomi/youpin/k8s/K8s.java
- jcommon/mybatis-plugins/src/main/java/run/mone/mybatis/plugin/AppNameInterceptor.java
> k8s启动初始化失败，抛出异常&Interceptor优化

- jcommon/prometheus/pom.xml
Remove redundant module declarations
> Remove redundant module declarations

- hera-all/milog/log-common/src/main/java/com/xiaomi/mone/log/common/Constant.java
- hera-all/milog/log-manager/src/main/resources/sql/log-data.sql
- hera-all/milog/log-manager/src/main/resources/sql/log.sql
- hera-all/milog/log-stream/src/main/java/com/xiaomi/mone/log/stream/bootstrap/MiLogStreamBootstrap.java
- hera-all/milog/log-stream/src/main/java/com/xiaomi/mone/log/stream/util/StreamUtils.java
- hera-all/milog/log-stream/src/main/resources/config.properties
- hera-all/milog/log-stream/src/main/resources/config/open.properties
> feat: stream start registration into nacos

- jcommon/mv-plugin/codecheck-maven-plugin/pom.xml
- jcommon/mv-plugin/codecheck-maven-plugin/src/main/java/run/mone/PmdMojo.java
codecheck plugin can not set white
> [feature]修改PmdMojo

- hera-all/milog/log-common/src/main/java/com/xiaomi/mone/log/common/Constant.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/bootstrap/MiLogManagerBootstrap.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/common/MilogConfig.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/controller/TestController.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/MilogConfigNacosService.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogConfigNacosServiceImpl.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogStreamServiceImpl.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/nacos/FetchStreamMachineService.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/nacos/MultipleNacosConfig.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/nacos/impl/NacosFetchStreamMachineService.java
- hera-all/milog/log-manager/src/test/java/com/xiaomi/mone/log/manager/test/ConfigNacosServiceTest.java
find stream mahine unique info
> feat: manger find stream machine info

- hera-all/trace-etl/pom.xml
- hera-all/trace-etl/trace-etl-common/pom.xml
- hera-all/trace-etl/trace-etl-service/pom.xml
upgrade log4j、logback、slf4j、fastjson version
> Deal trace-etl-common security

- jcommon/openai/src/test/java/run/mone/openapi/OpenApiTest.java
> add api key

- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/demo/hera_demo_client.yml
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/hera-fe/hera_fe.yml
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/log-agent-server/hera_log_agent-server.yml
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/log-manager/hera_log_manager.yml
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/log-stream/hera_log_stream.yml
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/nacos/config/mi_tpc_login_#_DEFAULT_GROUP.properties
- hera-all/hera-operator/hera-operator-service/src/main/java/run/mone/hera/operator/service/HeraBootstrapInitService.java
upgrade image version; add log-agent-server
> upgrade hera-operator

- hera-all/prometheus-starter-all/prometheus-diy-starter/src/main/java/com/xiaomi/mione/prometheus/starter/all/service/MilinePrometheusService.java
update customize metrics get ip env
> update customize metrics get ip env

- hera-all/opentelemetry-java-instrumentation/javaagent-tooling/javaagent-tooling.gradle
- hera-all/opentelemetry-java-instrumentation/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/AgentInstaller.java
otel set env and jvm properties
> otel set env and jvm properties

- hera-all/opentelemetry-java/exporters/jaeger/src/main/java/io/opentelemetry/exporter/jaeger/JaegerGrpcSpanExporter.java
- hera-all/opentelemetry-java/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/Log4j2Factory.java
- hera-all/opentelemetry-java/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LogFileNameUtil.java
- hera-all/opentelemetry-java/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/SpanToLogUtil.java
- hera-all/opentelemetry-java/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- hera-all/opentelemetry-java/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java
- hera-all/opentelemetry-java/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/TracerProviderConfiguration.java
- hera-all/opentelemetry-java/sdk/common/src/main/java/io/opentelemetry/sdk/common/EnvOrJvmProperties.java
- hera-all/opentelemetry-java/sdk/common/src/main/java/io/opentelemetry/sdk/common/HeraJavaagentConfig.java
- hera-all/opentelemetry-java/sdk/common/src/main/java/io/opentelemetry/sdk/common/HeraJavaagentConfigType.java
- hera-all/opentelemetry-java/sdk/common/src/main/java/io/opentelemetry/sdk/common/SystemCommon.java
> update opentelemetry-java env

- hera-all/hera-tspandata/pom.xml
> upgrade thrift version

- hera-all/hera-operator/hera-operator-server/Dockerfile
update hera-operator dockerfile
> update hera-operator dockerfile

- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/common/ManagerConstant.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/controller/interceptor/HttpRequestInterceptor.java
获取space的页面的url写入tpc登录界面的url到head中
> feat: space/getbypage url写入header

- hera-all/milog/log-stream/src/main/java/com/xiaomi/mone/log/stream/config/ConfigManager.java
- hera-all/milog/log-stream/src/main/java/com/xiaomi/mone/log/stream/config/MilogConfigListener.java
- hera-all/milog/log-stream/src/main/java/com/xiaomi/mone/log/stream/service/StreamAgent.java
> feat: stream unique mark update

- hera-all/milog/log-stream/src/main/java/com/xiaomi/mone/log/stream/common/util/StreamUtils.java
> feat: stream unique mark capture the last part

- hera-all/milog/log-stream/src/main/java/com/xiaomi/mone/log/stream/plugin/es/EsPlugin.java
compatible es pass and user null
> feat: es plugin user and pass compatible null

- hera-all/milog/log-agent/src/test/java/com/xiaomi/mone/log/agent/rpc/processor/service/RpcTest.java
> feat: clean unit test

- hera-all/milog/log-agent-server/pom.xml
- hera-all/milog/log-agent-server/src/main/resources/config/open.properties
- hera-all/milog/log-manager/pom.xml
- hera-all/milog/pom.xml
> update map-struct version

- hera-all/trace-etl/trace-etl-es/dockerfile
- hera-all/trace-etl/trace-etl-manager/dockerfile
- hera-all/trace-etl/trace-etl-server/dockerfile
> update trace-etl dockerfile

- hera-all/opentelemetry-java-instrumentation/instrumentation/apache-dubbo-2.7/library/src/main/java/io/opentelemetry/instrumentation/apachedubbo/v2_7/DubboTracer.java
remove otel setRpcServerName method, to fix Dubbo high level may be NPE.
> remove otel setRpcServerName method

- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/common/MilogConfig.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/dictionary/DictionaryExtensionServiceFactory.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/resource/ResourceExtensionServiceFactory.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/extension/tail/TailExtensionServiceFactory.java
- hera-all/milog/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogDictionaryServiceImpl.java
> update method name

- hera-all/trace-etl/trace-etl-server/src/main/java/com/xiaomi/hera/trace/etl/util/prometheus/HTTPServer.java
- hera-all/trace-etl/trace-etl-server/src/main/resources/application.properties
- hera-all/trace-etl/trace-etl-server/src/main/resources/config/opensource-outer.properties
trace-etl-server prometheus-token move to nacos
> prometheus-token move to nacos

- jcommon/es/pom.xml
- jcommon/es/src/main/java/com/xiaomi/mone/es/EsClient.java
add EsClient contain node select
> EsClient contain node select

- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/alertmanager/AlertManager.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/alertmanager/AlertServiceAdapt.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/alertmanager/impl/AlertManagerImpl.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/alertmanager/impl/MiCloudAlertManager.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/prometheus/AlarmService.java
update alarm rule param and method
> update alarm rule param and method

- hera-all/mimonitor/mimonitor-server/src/main/java/com/xiaomi/mone/monitor/controller/PrometheusController.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/es/EsExtensionService.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/es/EsExtensionServiceImpl.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/es/EsService.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/service/model/AppMonitorModel.java
mimonitor add EsExtensionService
> mimonitor add EsExtensionService

- hera-all/opentelemetry-java-instrumentation/dependencyManagement/dependencyManagement.gradle.kts
- hera-all/opentelemetry-java-instrumentation/instrumentation/apache-dubbo-2.7/library/src/main/java/io/opentelemetry/instrumentation/apachedubbo/v2_7/DubboTracer.java
upgrade otel-sdk version; remove unused
> upgrade otel-sdk version

- hera-all/opentelemetry-java/build.gradle.kts
- hera-all/opentelemetry-java/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LogFileNameUtil.java
- hera-all/opentelemetry-java/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
- hera-all/opentelemetry-java/sdk/common/src/main/java/io/opentelemetry/sdk/common/EnvOrJvmProperties.java
otel-sdk add env: MIONE_PROJECT_NAME
> otel-sdk add env

- hera-all/hera-webhook/.gitignore
- hera-all/hera-webhook/hera-webhook-server/dockerfile
- hera-all/hera-webhook/hera-webhook-server/pom.xml
- hera-all/hera-webhook/hera-webhook-server/src/main/java/run/mone/hera/webhook/Bootstrap.java
- hera-all/hera-webhook/hera-webhook-server/src/main/java/run/mone/hera/webhook/common/FileUtils.java
- hera-all/hera-webhook/hera-webhook-server/src/main/java/run/mone/hera/webhook/common/K8sUtilBean.java
- hera-all/hera-webhook/hera-webhook-server/src/main/java/run/mone/hera/webhook/controller/HeraWebhookController.java
- hera-all/hera-webhook/hera-webhook-server/src/main/java/run/mone/hera/webhook/domain/JsonPatch.java
- hera-all/hera-webhook/hera-webhook-server/src/main/java/run/mone/hera/webhook/service/HeraWebhookService.java
- hera-all/hera-webhook/hera-webhook-server/src/main/resources/application.properties
- hera-all/hera-webhook/hera-webhook-server/src/main/resources/hera_init/webhook/csr/webhook_csr.yaml
- hera-all/hera-webhook/hera-webhook-server/src/main/resources/hera_init/webhook/hera_webhook_config.yaml
- hera-all/hera-webhook/hera-webhook-server/src/main/resources/logback.xml
- hera-all/hera-webhook/pom.xml
add hera-webhook server project
> hera-webhook server project

- hera-all/hera-operator/hera-operator-common/src/main/java/run/mone/hera/operator/common/FileUtils.java
- hera-all/hera-operator/hera-operator-common/src/main/java/run/mone/hera/operator/common/HoConstant.java
- hera-all/hera-operator/hera-operator-common/src/main/java/run/mone/hera/operator/common/ResourceTypeEnum.java
- hera-all/hera-operator/hera-operator-server/pom.xml
- hera-all/hera-operator/hera-operator-server/src/main/java/run/mone/hera/operator/controller/HeraOperatorController.java
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/log-agent-server/hera_log_agent-server.yml
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/log-manager/hera_log_manager.yml
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/nacos/config/hera_log_manager_open_#_DEFAULT_GROUP.properties
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/nacos/config/log_stream_dataId_open_#_DEFAULT_GROUP.properties
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/webhook/hera_webhook_server.yaml
- hera-all/hera-operator/hera-operator-server/src/main/resources/operator/hera_operator_deployment.yaml
- hera-all/hera-operator/hera-operator-service/src/main/java/run/mone/hera/operator/service/HeraBootstrapInitService.java
- hera-all/hera-operator/hera-operator-service/src/main/java/run/mone/hera/operator/service/NacosService.java
- hera-all/hera-operator/hera-operator-service/src/main/java/run/mone/hera/operator/service/RocketMQSerivce.java
- hera-all/hera-operator/pom.xml
> operator add webhook

- hera-all/mimonitor/mimonitor-server/src/main/java/com/xiaomi/mone/monitor/controller/GrafanaMappingController.java
- hera-all/mimonitor/mimonitor-service/src/main/java/com/xiaomi/mone/monitor/bo/PlatFormType.java
update platFormType getCodeByGrafanaDir to getCodeByName
> Dev 0420 02

- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/AppGrafanaMappingService.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/serverless/ServerLessService.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/serverless/impl/ServerLessServiceImpl.java
extension for serverless getFaasFunctionList
> serverless extension

- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/AppAlarmService.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/api/AppAlarmServiceExtension.java
> AppAlarmService extension

- hera-all/hera-log/log-api/src/main/java/com/xiaomi/mone/log/api/service/MilogOpenService.java
- hera-all/hera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/HeraAppService.java
- hera-all/hera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/HeraAppServiceImpl.java
- hera-all/hera-log/log-manager/src/main/java/com/xiaomi/mone/log/manager/service/impl/MilogOpenServiceImpl.java
- hera-all/hera-log/log-manager/src/test/java/com/xiaomi/mone/log/manager/service/impl/MilogOpenServiceTest.java
- hera-all/hera-log/pom.xml
> update have accsss log system 

- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/AppGrafanaMappingService.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/AppGrafanaMappingServiceExtensionImpl.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/api/AppGrafanaMappingServiceExtension.java
add AppGrafanaMappingServiceExtension
> add AppGrafanaMappingServiceExtension

- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/AppAlarmService.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/AppAlarmServiceExtensionImpl.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/api/AlarmServiceExtension.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/api/AppAlarmServiceExtension.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/prometheus/AlarmService.java
- hera-all/hera-monitor/hera-monitor-service/src/main/java/com/xiaomi/mone/monitor/service/prometheus/AlarmServiceExtensionImpl.java
update AlarmService and AppAlarmService abort openSource and inner code
> update AlarmService and AppAlarmService abort openSource and inner code

- hera-all/hera-app/app-server/Dockerfile
- hera-all/hera-app/app-server/src/main/resources/Dockerfile
> update hera-app dockerfile

- hera-all/trace-etl/pom.xml
- hera-all/trace-etl/trace-etl-common/pom.xml
- hera-all/trace-etl/trace-etl-domain/src/main/java/com/xiaomi/hera/trace/etl/domain/tracequery/TraceListQueryVo.java
- hera-all/trace-etl/trace-etl-manager/src/main/resources/config/opensource-outer.properties
- hera-all/trace-etl/trace-etl-service/src/main/java/com/xiaomi/hera/trace/etl/service/QueryEsService.java
trace-etl-manager add query by env
> trace-etl-manager add query by env

- hera-all/hera-app/app-api/pom.xml
- hera-all/hera-app/app-server/pom.xml
> update hera-app pom

- hera-all/hera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/channel/locator/ChannelDefineRpcLocator.java
- hera-all/hera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/factory/OutPutServiceFactory.java
- hera-all/hera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/service/ChannelDefineLocatorExtension.java
- hera-all/hera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/service/impl/OuterChannelDefineLocatorExtensionImpl.java
add ChannelDefineLocatorExtension
> add ChannelDefineLocatorExtension

- jcommon/hera/hera-trace/src/main/java/com/xiaomi/hera/trace/context/ThreadPool/CallBack.java
- jcommon/hera/hera-trace/src/main/java/com/xiaomi/hera/trace/context/ThreadPool/ThreadPoolExport.java
- jcommon/hera/hera-trace/src/main/java/com/xiaomi/hera/trace/context/ThreadPool/ThreadpoolConfig.java
> threadpool

- hera-all/trace-etl/trace-etl-server/src/main/java/com/xiaomi/hera/trace/etl/consumer/ConsumerService.java
- hera-all/trace-etl/trace-etl-service/src/main/java/com/xiaomi/hera/trace/etl/mq/rocketmq/ClientMessageQueue.java
> Modify English notes

- jcommon/docean-plugin/docean-plugin-mybatis/src/main/java/com/xiaomi/youpin/docean/plugin/mybatis/MybatisPlugin.java
- jcommon/easy/src/main/java/com/xiaomi/youpin/docean/common/ReflectUtils.java
> mybatis+easy

- hera-all/hera-webhook/hera-webhook-server/src/main/java/run/mone/hera/webhook/Bootstrap.java
delete webhook when webhook server is shutdown
> delete webhook when webhook server is shutdown

- hera-all/trace-etl/trace-etl-service/src/main/java/com/xiaomi/hera/trace/etl/mq/rocketmq/ClientMessageQueue.java
- hera-all/trace-etl/trace-etl-service/src/main/java/com/xiaomi/hera/trace/etl/mq/rocketmq/ClientMessageQueueWrapper.java
fix RocketMQ multi-broker Exception in trace-etl-server
> fix RocketMQ multi-broker Exception

- hera-all/trace-etl/trace-etl-service/src/main/java/com/xiaomi/hera/trace/etl/mq/rocketmq/ClientMessageQueue.java
- hera-all/trace-etl/trace-etl-service/src/main/java/com/xiaomi/hera/trace/etl/mq/rocketmq/ClientMessageQueueWrapper.java
convert annotation to English from Chinese
> convert English annotation

- hera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/queue/impl/RocksdbStoreServiceImpl.java
- hera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/util/bloomfilter/BloomFilterHelper.java
- hera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/util/bloomfilter/TraceIdRedisBloomUtil.java
- hera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/util/redis/RedisClientUtil.java
- hera-all/trace-etl/trace-etl-manager/src/main/java/com/xiaomi/hera/trace/etl/manager/config/DataSourceConfig.java
- hera-all/trace-etl/trace-etl-manager/src/main/java/com/xiaomi/hera/trace/etl/manager/controller/ManagerController.java
transform bloomfilter relation service
> transform bloomfilter relation service

- hera-all/hera-operator/hera-operator-service/src/main/java/run/mone/hera/operator/handler/HeraResourceEventHandler.java
- hera-all/hera-operator/hera-operator-service/src/main/java/run/mone/hera/operator/service/RocketMQSerivce.java
> transform hera operator

- hera-all/hera-prometheus-agent/hera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/alarmContact/FeishuAlertContact.java
- hera-all/hera-prometheus-agent/hera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/alarmContact/MailAlertContact.java
- hera-all/hera-prometheus-agent/hera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/impl/PrometheusDubboServiceImpl.java
- hera-all/hera-prometheus-agent/hera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/impl/PrometheusIpServiceImpl.java
- hera-all/hera-prometheus-agent/hera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/prometheus/RuleAlertService.java
- hera-all/hera-prometheus-agent/hera-prometheus-agent-service/src/main/java/com/xiaomi/youpin/prometheus/agent/service/prometheus/RuleSilenceService.java
> transform prometheus agent

- hera-all/trace-etl/trace-etl-service/pom.xml
> update trace-etl es version

- hera-all/hera-demo-client/hera-demo-client-api/pom.xml
- hera-all/hera-demo-client/hera-demo-client-server/pom.xml
- hera-all/hera-demo-client/hera-demo-client-server/src/main/resources/config/open-source.properties
- hera-all/hera-demo-client/hera-demo-client-service/pom.xml
- hera-all/hera-demo-client/hera-demo-client-service/src/main/java/com/xiaomi/mone/hera/demo/client/service/DubboHealthServiceImpl.java
- hera-all/hera-demo-server/pom.xml
> update pom, delete dependency

- hera-all/hera-demo-server/LICENSE.txt
- hera-all/hera-demo-server/hera-demo-server-api/src/main/resources/META-INF/LICENSE.txt
- hera-all/hera-demo-server/hera-demo-server-server/src/main/resources/META-INF/LICENSE.txt
- hera-all/hera-demo-server/pom.xml
> add hera-demo-server license

- hera-all/hera-demo-client/LICENSE.txt
- hera-all/hera-demo-client/hera-demo-client-api/src/main/resources/META-INF/LICENSE.txt
- hera-all/hera-demo-client/hera-demo-client-common/pom.xml
- hera-all/hera-demo-client/hera-demo-client-common/src/main/resources/META-INF/LICENSE.txt
- hera-all/hera-demo-client/hera-demo-client-server/src/main/resources/META-INF/LICENSE.txt
- hera-all/hera-demo-client/hera-demo-client-service/src/main/resources/META-INF/LICENSE.txt
- hera-all/hera-demo-client/pom.xml
> add hera-demo-client license

- hera-all/hera-tspandata/LICENSE.txt
- hera-all/hera-tspandata/pom.xml
[add hera-tspandata license](https://github.com/XiaoMi/mone/commit/761f3384b57e68cf3017a0aa6dcf49ba966a6b50)
> add hera-tspandata license

- hera-all/trace-etl/LICENSE.txt
- hera-all/trace-etl/pom.xml
- hera-all/trace-etl/trace-etl-api/src/main/resources/META-INF/LICENSE.txt
- hera-all/trace-etl/trace-etl-common/src/main/resources/META-INF/LICENSE.txt
- hera-all/trace-etl/trace-etl-dao/src/main/resources/META-INF/LICENSE.txt
- hera-all/trace-etl/trace-etl-domain/src/main/resources/META-INF/LICENSE.txt
- hera-all/trace-etl/trace-etl-es/src/main/resources/META-INF/LICENSE.txt
- hera-all/trace-etl/trace-etl-manager/src/main/resources/META-INF/LICENSE.txt
- hera-all/trace-etl/trace-etl-nginx/src/main/resources/META-INF/LICENSE.txt
- hera-all/trace-etl/trace-etl-server/src/main/resources/META-INF/LICENSE.txt
- hera-all/trace-etl/trace-etl-service/src/main/resources/META-INF/LICENSE.txt
> add trace-etl license

- hera-all/hera-webhook/LICENSE.txt
- hera-all/hera-webhook/hera-webhook-server/src/main/resources/META-INF/LICENSE.txt
- hera-all/hera-webhook/pom.xml
> add hera-webhook license

- hera-all/hera-demo-server/hera-demo-server-server/pom.xml
- hera-all/hera-demo-server/pom.xml
update hera-demo-server spring-context-support to run.mone
> update hera-demo-server spring-context-support

- hera-all/hera-demo-client/hera-demo-client-server/pom.xml
- hera-all/hera-demo-client/hera-demo-client-service/pom.xml
update hera-demo-client spring-context-support to run.mone
> update hera-demo-client spring-context-support

- hera-all/hera-demo-server/pom.xml
> update release to SNAPSHOT

- hera-all/trace-etl/trace-etl-service/pom.xml
update trace-etl spring-context-support
> update trace-etl spring-context-support

- hera-all/opentelemetry-java-instrumentation/instrumentation/apache-dubbo-2.7/javaagent/apache-dubbo-2.7-javaagent.gradle
- hera-all/opentelemetry-java-instrumentation/instrumentation/apache-dubbo-2.7/library/apache-dubbo-2.7-library.gradle
- hera-all/opentelemetry-java-instrumentation/instrumentation/apache-dubbo-2.7/testing/apache-dubbo-2.7-testing.gradle
delete opentelemetry dependency spring-context-support
> delete opentelemetry dependency spring-context-support

- hera-all/hera-operator/hera-operator-server/pom.xml
- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/mysql/hera_mysql.yaml
> docean add spring dependency

- jcommon/prometheus/pom.xml
- jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/multi/MutiMetrics.java
- jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/multi/MutiPrometheus.java
> Feat multi metrics 20230829

- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/nacos/config/hera_app_config_#_DEFAULT_GROUP.properties
- hera-all/hera-operator/hera-operator-service/src/main/java/run/mone/hera/operator/service/RocketMQSerivce.java
> add hera_meta_data topic

- jcommon/prometheus/prometheus-trace-etl/src/main/java/com/xiaomi/youpin/prometheus/client/multi/MutiMetrics.java
> translate MultiMetrics

- jcommon/rcurve/pom.xml
> [feature]upgrade rcurve version

- hera-all/hera-operator/hera-operator-server/src/main/resources/hera_init/nacos/config/hera_trace_config_#_DEFAULT_GROUP.properties
- hera-all/trace-etl/trace-etl-common/pom.xml
- hera-all/trace-etl/trace-etl-server/src/main/java/com/xiaomi/hera/trace/etl/consumer/ConsumerService.java
- hera-all/trace-etl/trace-etl-server/src/main/java/com/xiaomi/hera/trace/etl/consumer/DataCacheService.java
- hera-all/trace-etl/trace-etl-server/src/main/java/com/xiaomi/hera/trace/etl/consumer/EnterManager.java
- hera-all/trace-etl/trace-etl-server/src/main/java/com/xiaomi/hera/trace/etl/util/prometheus/HTTPServer.java
- hera-all/trace-etl/trace-etl-service/src/main/java/com/xiaomi/hera/trace/etl/mq/rocketmq/ClientMessageQueue.java
- hera-all/trace-etl/trace-etl-service/src/main/java/com/xiaomi/hera/trace/etl/mq/rocketmq/ClientMessageQueueWrapper.java
hera_trace_config add prometheus.pull.header
> hera_trace_config add prometheus.pull.header

- .github/workflows/hera_package.yml
- .github/workflows/jcommon_package.yml
> java 20 build action

- ozhera-all/README.md
- ozhera-all/README_CN.md
> translate OzHera README to EN

- ozhera-all/readme/deploy/ozhera-deploy-document.md
- ozhera-all/readme/deploy/ozhera-deploy-document_cn.md
translate OzHera deploy doc to EN
> translate OzHera deploy doc to EN

- ozhera-all/readme/best-practices/deployment.md
- ozhera-all/readme/best-practices/deployment_cn.md
translate OzHera best-practices doc to EN
> translate OzHera best-practices doc to EN

- ozhera-all/README_CN.md
- ozhera-all/readme/application-integeration/application-integration-document.md
- ozhera-all/readme/application-integeration/application-integration-document_cn.md
translate OzHera integration doc to EN
> translate OzHera integration doc to EN

- ozhera-all/opentelemetry-java/README.md
- ozhera-all/opentelemetry-java/README_cn.md
translate opentelemetry-java readme
> translate opentelemetry-java readme

- ozhera-all/opentelemetry-java-instrumentation/README.md
- ozhera-all/opentelemetry-java-instrumentation/README_cn.md
translate opentelemetry-java-instrumentation readme
> translate opentelemetry-java-instrumentation readme

- ozhera-all/ozhera-log/README.md
- ozhera-all/ozhera-log/README_cn.md
> translate log readme

- ozhera-all/opentelemetry-java/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/Log4j2Factory.java
- ozhera-all/opentelemetry-java/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/Log4j2SpanExporter.java
- ozhera-all/opentelemetry-java/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LogFileNameUtil.java
- ozhera-all/opentelemetry-java/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/SpanToLogUtil.java
- ozhera-all/opentelemetry-java/exporters/prometheus/src/main/java/io/opentelemetry/exporter/prometheus/MetricAdapter.java
- ozhera-all/opentelemetry-java/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/MetricExporterConfiguration.java
translate opentelemetry-java anno
> translate opentelemetry-java anno

- ozhera-all/opentelemetry-java-instrumentation/instrumentation/hera/javaagent/src/main/java/io/opentelemetry/javaagent/instrumentation/hera/HeraContextInstrumentation.java
translate opentelemetry-java-instrumentation anno
> translate opentelemetry-java-instrumentation anno

- ozhera-all/trace-etl/trace-etl-common/src/main/java/com/xiaomi/hera/trace/etl/common/HashUtil.java
- ozhera-all/trace-etl/trace-etl-common/src/main/java/com/xiaomi/hera/trace/etl/common/TimeConverter.java
> translate trace-etl anno

- ozhera-all/ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/alertManager/ozhera_alertmanager.yaml
- ozhera-all/ozhera-operator/ozhera-operator-server/src/main/resources/ozhera_init/mysql/sql/nacos.sql
- ozhera-all/ozhera-operator/ozhera-operator-service/src/main/java/run/mone/hera/operator/service/HeraBootstrapInitService.java
> translate operator 2

- ozhera-all/trace-etl/trace-etl-api/src/main/java/com/xiaomi/hera/trace/etl/api/service/TraceManagerService.java
- ozhera-all/trace-etl/trace-etl-es/README.md
- ozhera-all/trace-etl/trace-etl-es/README_CN.md
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/config/DataSourceConfig.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/config/EsProcessConfig.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/config/ServiceConfiguration.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/config/TraceConfig.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/consumer/ConsumerService.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/consumer/FilterService.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/consumer/TraceSpanConsumer.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/domain/FilterResult.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/domain/FutureRequest.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/domain/LocalStorages.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/dubbo/TraceEtlServiceImpl.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/queue/impl/RocksdbStoreServiceImpl.java
- ozhera-all/trace-etl/trace-etl-es/src/main/java/com/xiaomi/hera/trace/etl/es/queue/impl/TeSnowFlake.java
> translate trace-etl

- jcommon/docean-plugin/docean-plugin-es-antlr4/src/main/java/com/xiaomi/youpin/docean/plugin/es/antlr4/impl/EsQueryTransfer.java
class EsQueryTransfer translate
#702
> translate cn to en

- jcommon/docean-plugin/docean-plugin-es-antlr4/src/main/java/com/xiaomi/youpin/docean/plugin/es/antlr4/impl/EsQueryTransfer.java
> fixes #705   

- jcommon/rcurve/pom.xml
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/common/ExecutorServiceUtils.java
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsClient.java
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsServer.java
rcurve support VirtualThread
close #710
> rcurve support VirtualThread

- jcommon/docean-spring-starter/src/main/java/run/mone/docean/spring/config/DoceanAutoConfigure.java
> update multi extension

- jcommon/codecheck/pom.xml
- jcommon/es/pom.xml
- jcommon/graalvm/pom.xml
- jcommon/infra-result/src/main/java/com/xiaomi/youpin/infra/rpc/errors/ErrorCode.java
- jcommon/infra-result/src/main/java/com/xiaomi/youpin/infra/rpc/errors/ErrorScope.java
- jcommon/jmonitor/pom.xml
- jcommon/monitor/pom.xml
- jcommon/mv-plugin/codecheck-maven-plugin/pom.xml
- jcommon/mv-plugin/jarcheck-maven-plugin/pom.xml
- jcommon/mv-plugin/native-plugin/pom.xml
- jcommon/pom.xml
- jcommon/processor/pom.xml
- jcommon/prometheus/prometheus-client/pom.xml
- jcommon/prometheus/prometheus-trace-etl/pom.xml
- jcommon/rcurve/pom.xml
modify jcommon compiler version
close #728
> modify jcommon compiler version

- .github/workflows/jcommon_package.yml
add jdk-21 workflow
close #735
> add jdk-21 workflow

- jcommon/docean-plugin/docean-plugin-log/src/test/java/com/xiaomi/youpin/docean/plugin/log/test/LogWriterTest.java
- jcommon/file/pom.xml
- jcommon/file/src/test/java/com/xiaomi/mone/file/LogFileTest.java
- jcommon/file/src/test/java/com/xiaomi/mone/file/RandomAccessFileTest.java
The file module needs to add a few performance-related unit tests. #731
> The file module needs to add a few performance-related unit tests. #731

- ozhera-all/README.md
- ozhera-all/README_CN.md
> split ozhera (#737)

- jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/thread/ThreadTest.java
> add virtual thread test

- ozhera-all/ozhera-log/log-agent/pom.xml
- ozhera-all/ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/KafkaExporter.java
- ozhera-all/ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/KafkaMQService.java
- ozhera-all/ozhera-log/log-agent/src/main/java/com/xiaomi/mone/log/agent/extension/KafkaOutput.java
> apply kafka

- jcommon/docean/README.md
- jcommon/docean/pom.xml
- jcommon/docean/src/main/java/com/xiaomi/youpin/docean/Mvc.java
- jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/Get.java
- jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/httpmethod/HttpMethodUtils.java
> Revert "fix: fix for Git request parameter problem"

- jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/Post.java
> fix: post param array problem

- jcommon/docean-plugin/docean-plugin-k8s/pom.xml
- jcommon/docean-plugin/docean-plugin-k8s/src/main/java/run/mone/docean/plugin/k8s/K8sPlugin.java
- jcommon/file/pom.xml
- jcommon/hera/pom.xml
> release oz ref #777

- jcommon/prometheus/prometheus-trace-etl/pom.xml
feat: add prometheus-trace-etl release
> feat: add prometheus-trace-etl release

- jcommon/codecheck/pom.xml
- jcommon/codegen/src/main/resources/template/docean_pom.tml
- jcommon/codegen/src/main/resources/template/filter_pom.tml
- jcommon/codegen/src/main/resources/template/plugin_pom.tml
- jcommon/codegen/src/main/resources/template/springboot_pom.tml
- jcommon/graalvm/pom.xml
- jcommon/mv-plugin/codecheck-maven-plugin/pom.xml
> codecheck update

- jcommon/rpc-codes/src/main/java/com/xiaomi/data/push/uds/codes/DefaultHessian2FactoryInitializer.java
- jcommon/rpc-codes/src/main/java/com/xiaomi/data/push/uds/codes/HessianCodes.java
SerializerFactory when use hessian
> SerializerFactory when use hessian

- jcommon/es/src/main/java/com/xiaomi/mone/es/EsClient.java
- jcommon/es/src/test/java/com/xiaomi/mone/es/test/EsClientTest.java
- jcommon/file/src/main/java/com/xiaomi/mone/file/ozhera/HeraFileMonitor.java
- jcommon/file/src/test/java/com/xiaomi/mone/file/LogFileTest.java
#824 
"Fix Log Monitoring Bug"
> fix: Log Collection and Monitoring bug

- jcommon/ai/bytedance/pom.xml
- jcommon/ai/bytedance/src/main/java/run/mone/ai/bytedance/ArsClientOut.java
- jcommon/ai/bytedance/src/main/java/run/mone/ai/bytedance/ArsRequest.java
- jcommon/ai/bytedance/src/main/java/run/mone/ai/bytedance/AsrClient.java
- jcommon/ai/bytedance/src/test/java/run/mone/ai/bytedance/test/ArsTest.java
- jcommon/ai/pom.xml
> speech2text

- jcommon/ai/google/src/main/java/run/mone/ai/google/CloudeClient.java
> api update

- jcommon/ai/google/src/main/java/run/mone/ai/google/CloudeClient.java
> feat: claudeclient adjustment

- jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/controller/UserController.java
JCommon MongoDB UserController set default role at login
> [enhancement] JCommon MongoDB UserController set default role at login

- jcommon/docean-plugin/docean-plugin-mongodb/src/main/java/run/mone/service/MongoService.java
JCommon MongoDB MongoService add option for delete
> [enhancement] JCommon MongoDB MongoService add option for delete

- jcommon/docean/src/main/java/com/xiaomi/youpin/docean/mvc/session/HttpSessionManager.java
- jcommon/docean/src/test/java/com/xiaomi/youpin/docean/test/MapTest.java
[enhancement] Enhance Session Expiry Time for Docean
> [enhancement] Enhance Session Expiry Time for Docean

- jcommon/sysFunc/src/main/java/run/mone/sysFunc/SysFuncUtils.java
#867 
Add exclusion functionality to the random string method in SysFuncUtils
> Add exclusion functionality to the random string method in SysFuncUtils

- jcommon/ai/neo4j/pom.xml
- jcommon/ai/neo4j/src/main/java/run/mone/neo4j/MoneCodeParser.java
- jcommon/ai/neo4j/src/test/java/run/mone/neo4j/test/A.java
- jcommon/ai/neo4j/src/test/java/run/mone/neo4j/test/MoneCodeParserTest.java
- jcommon/pom.xml
- Updated A.java and MoneCodeParserTest.java in neo4j test directory
- Updated MoneCodeParser.java in neo4j main directory
- Updated pom.xml in neo4j and jcommon directories
> chore: update project dependencies and test files

- jcommon/gitlab/src/main/java/com/xiaomi/youpin/gitlab/Gitlab.java
> [enhancement] gitlab clone from private to public

- jcommon/ai/google/src/main/java/run/mone/ai/google/bo/RequestPayload.java
claude3.5 supports system prompt
> chore: update RequestPayload.java with no content changes

- jcommon/ai/neo4j/src/main/java/run/mone/neo4j/MoneCodeParser.java
- jcommon/ai/neo4j/src/main/java/run/mone/neo4j/MoneMethodCodeParser.java
- jcommon/ai/neo4j/src/test/java/run/mone/neo4j/test/MoneCodeParserTest.java
- jcommon/ai/neo4j/src/test/java/run/mone/neo4j/test/m/cat/CatService.java
chore: update test and main classes without code changes
> chore: update test and main classes without code changes

- jcommon/rcurve/src/test/java/com/xiaomi/mone/rcurve/test/UdsTest.java
feat: mesh streaming response support
>  feat: mesh streaming response support

- jcommon/pom.xml
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/common/NetUtils.java
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsClient.java
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsServer.java
> [fix] mesh remote 问题修复

- jcommon/easy/src/main/java/com/xiaomi/youpin/docean/common/ReflectUtils.java
- jcommon/pom.xml
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/common/NetUtils.java
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsClient.java
- jcommon/rcurve/src/main/java/com/xiaomi/data/push/uds/UdsServer.java
> [fix] ReflectUtils String 优化

- jcommon/docean-plugin/docean-plugin-sidecar/pom.xml
- jcommon/rcurve/pom.xml
chore: update UdsClient.java without any changes
> chore: update UdsClient.java without any changes

- jcommon/ai/mcp/pom.xml
- jcommon/ai/mcp/src/main/java/run/mone/ai/mcp/Client.java
- jcommon/ai/mcp/src/main/java/run/mone/ai/mcp/ServerConfig.java
- jcommon/ai/mcp/src/test/java/run/mone/ai/mcp/TestClient.java
- jcommon/pom.xml
> [feature] JCommon ai MCP client

- jcommon/hive/pom.xml
- jcommon/hive/src/main/java/run/mone/hive/mcp/client/McpAsyncClient.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/client/McpClient.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/client/McpSyncClient.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/client/transport/FlowSseClient.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/client/transport/HttpClientSseClientTransport.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/client/transport/ServerParameters.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/client/transport/StdioClientTransport.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/demo/McpBootstrap.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/demo/McpConfig.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/demo/SimpleMcpClient.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/demo/SimpleMcpServer.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/server/McpAsyncServer.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/server/McpServer.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/server/McpSyncServer.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/server/transport/HttpServletSseServerTransport.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/server/transport/StdioServerTransport.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/ClientMcpTransport.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/DefaultMcpSession.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/McpError.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/McpSchema.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/McpSession.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/McpTransport.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/ServerMcpTransport.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/transport/webmvcsse/WebMvcSseServerTransport.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/util/Assert.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/util/Utils.java
add mcp protocal implementation  and demo server&client
> feat(mcp-support): add mcp protocal implementation 

- jcommon/hive/pom.xml
- jcommon/hive/src/main/java/run/mone/hive/mcp/demo/SimpleMcpClient.java
- jcommon/hive/src/main/java/run/mone/hive/planner/ActionFactory.java
- jcommon/hive/src/main/java/run/mone/hive/planner/OptimalTeamStrategy.java
- jcommon/hive/src/main/java/run/mone/hive/planner/TeamBuilder.java
feat(mcp-support): using stdio as transport
> feat(mcp-support): using stdio as transport

- jcommon/mcp/mcp-memory/pom.xml
- jcommon/mcp/mcp-memory/src/main/java/run/mone/mcp/memory/MemoryMcpBootstrap.java
- jcommon/mcp/mcp-memory/src/main/java/run/mone/mcp/memory/config/McpStdioTransportConfig.java
- jcommon/mcp/mcp-memory/src/main/java/run/mone/mcp/memory/function/MemoryFunctions.java
- jcommon/mcp/mcp-memory/src/main/java/run/mone/mcp/memory/graph/Entity.java
- jcommon/mcp/mcp-memory/src/main/java/run/mone/mcp/memory/graph/KnowledgeGraph.java
- jcommon/mcp/mcp-memory/src/main/java/run/mone/mcp/memory/graph/KnowledgeGraphManager.java
- jcommon/mcp/mcp-memory/src/main/java/run/mone/mcp/memory/graph/Relation.java
- jcommon/mcp/mcp-memory/src/main/java/run/mone/mcp/memory/server/MemoryMcpServer.java
- jcommon/mcp/mcp-memory/src/main/resources/application.properties
- jcommon/mcp/mcp-memory/src/test/java/run/mone/mcp/memory/test/MemoryFunctionsTest.java
- jcommon/mcp/mcp-memory/src/test/resources/application-test.properties
- jcommon/mcp/pom.xml
feat(mcp_memory): add mcp server for memory
> feat(mcp_memory): add mcp server for memory

- jcommon/hive/src/test/java/run/mone/hive/llm/LLMTest.java
> fix(config): add proxy config

- jcommon/mcp/mcp-sequentialthinking/pom.xml
- jcommon/mcp/mcp-sequentialthinking/src/main/java/run/mone/mcp/sequentialthinking/SequentialThinkingMcpBootstrap.java
- jcommon/mcp/mcp-sequentialthinking/src/main/java/run/mone/mcp/sequentialthinking/config/McpStdioTransportConfig.java
- jcommon/mcp/mcp-sequentialthinking/src/main/java/run/mone/mcp/sequentialthinking/function/SequentialThinkingFunction.java
- jcommon/mcp/mcp-sequentialthinking/src/main/java/run/mone/mcp/sequentialthinking/model/ProcessResult.java
- jcommon/mcp/mcp-sequentialthinking/src/main/java/run/mone/mcp/sequentialthinking/model/ThoughtData.java
- jcommon/mcp/mcp-sequentialthinking/src/main/java/run/mone/mcp/sequentialthinking/server/SequentialThinkingMcpServer.java
- jcommon/mcp/pom.xml
feat(mcp-sequential-thinking): add new server
> feat(mcp-sequential-thinking): add new server

- jcommon/moner/plugin/popup-vue/src/api/audio.ts
- jcommon/moner/plugin/popup-vue/src/components/common-message/Message/index.vue
- jcommon/moner/plugin/popup-vue/src/components/common-textarea/CommonTextarea.vue
- jcommon/moner/plugin/popup-vue/src/components/recorder/index.vue
- jcommon/moner/plugin/popup-vue/src/views/PopupView.vue
> feat: 语言转换

- jcommon/moner-server/src/main/java/run/mone/moner/server/history/AiMessageManager.java
- jcommon/moner-server/src/main/java/run/mone/moner/server/mcp/SseClient.java
> refacotr: add history manager

- jcommon/es/src/main/java/com/xiaomi/mone/es/EsClient.java
- jcommon/file/src/main/java/com/xiaomi/mone/file/ozhera/HeraFileMonitor.java
- jcommon/gitlab/src/main/java/com/xiaomi/youpin/gitlab/bo/GroupInfo.java
- jcommon/gitlab/src/test/java/com/xiaomi/youpin/gitlab/GitlabTest.java
> refactor: update common optimize

- jcommon/mcp/mcp-idea/pom.xml
- jcommon/mcp/mcp-idea/src/main/java/run/mone/mcp/idea/config/IdeaMcpConfig.java
- jcommon/mcp/mcp-idea/src/main/java/run/mone/mcp/idea/function/CodeReviewFunction.java
- jcommon/mcp/mcp-idea/src/main/java/run/mone/mcp/idea/server/IdeaMcpServer.java
- jcommon/mcp/mcp-idea/src/main/java/run/mone/mcp/idea/service/IdeaService.java
- jcommon/mcp/mcp-idea/src/main/resources/application.properties
- jcommon/mcp/mcp-idea/src/test/java/run/mone/mcp/idea/function/IdeaFunctionTest.java
update idea mcp code review function, call LLM
> update idea mcp code review function, call LLM

- jcommon/moner/plugin/background.js
> feat: 事件回调

- jcommon/mcp/mcp-chrome/src/main/java/run/mone/mcp/chrome/function/OpenTabFunction.java
- jcommon/mcp/mcp-chrome/src/main/java/run/mone/mcp/chrome/function/OperationFunction.java
- jcommon/moner-server/src/main/java/run/mone/moner/server/prompt/MonerSystemPrompt.java
- jcommon/moner-server/src/main/java/run/mone/moner/server/role/ChromeAthena.java
- jcommon/moner-server/src/main/java/run/mone/moner/server/websocket/WebSocketHandler.java
- jcommon/moner/plugin/background.js
- jcommon/moner/plugin/popup-vue/src/assets/markdown-mcp.scss
- jcommon/moner/plugin/popup-vue/src/components/common-message/markdown-it-plugin/mcp.ts
feat(chrome-athena): add observe machenism add fix chat
> feat(chrome-athena): add observe machenism add fix chat

- jcommon/hive/src/main/java/run/mone/hive/mcp/client/McpAsyncClient.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/client/McpSyncClient.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/demo/SimpleMcpClient.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/demo/SimpleMcpServer.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/demo/function/CalculatorFunction.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/server/McpAsyncServer.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/server/McpServer.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/server/McpSyncServer.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/DefaultMcpSession.java
- jcommon/hive/src/main/java/run/mone/hive/mcp/spec/McpSchema.java
- jcommon/hive/src/main/resources/application.properties
wip(stream-call-tool): stream call tool
> wip(stream-call-tool): stream call tool

- jcommon/mcp/mcp-novel/README.md
- jcommon/mcp/mcp-novel/pom.xml
- jcommon/mcp/mcp-novel/src/main/java/run/mone/mcp/novel/NovelMcpBootstrap.java
- jcommon/mcp/mcp-novel/src/main/java/run/mone/mcp/novel/config/NovelMcpConfig.java
- jcommon/mcp/mcp-novel/src/main/java/run/mone/mcp/novel/function/NovelFunction.java
- jcommon/mcp/mcp-novel/src/main/java/run/mone/mcp/novel/server/NovelMcpServer.java
- jcommon/mcp/mcp-novel/src/main/java/run/mone/mcp/novel/service/NovelService.java
- jcommon/mcp/mcp-novel/src/main/resources/application.properties
- jcommon/mcp/pom.xml
add novel-mcp, support summarizeNovel
> add novel-mcp, support summarizeNovel

- jcommon/mcp/mcp-miapi/README.md
- jcommon/mcp/mcp-miapi/pom.xml
- jcommon/mcp/mcp-miapi/src/main/java/run.mone.mcp.miapi/MiApiMcpBootStrap.java
- jcommon/mcp/mcp-miapi/src/main/java/run.mone.mcp.miapi/bo/ReqParamsBo.java
- jcommon/mcp/mcp-miapi/src/main/java/run.mone.mcp.miapi/config/McpStdioTransportConfig.java
- jcommon/mcp/mcp-miapi/src/main/java/run.mone.mcp.miapi/enums/ApiTypeEnum.java
- jcommon/mcp/mcp-miapi/src/main/java/run.mone.mcp.miapi/function/MiApiFunction.java
- jcommon/mcp/mcp-miapi/src/main/java/run.mone.mcp.miapi/http/HttpClient.java
- jcommon/mcp/mcp-miapi/src/main/java/run.mone.mcp.miapi/server/MiApiMcpServer.java
- jcommon/mcp/mcp-miapi/src/main/resources/application.properties
- jcommon/mcp/mcp-miapi/src/test/java/run/mone/mcp/miapi/function/MiApiFunctionTest.java
- jcommon/mcp/pom.xml
> feat: miapi mcp

- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/function/ComposerFunction.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/CodeGeneratePromptHolder.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/CodeGenerationHandler.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/CodePrompt.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/biz/BotChainCall.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/prompt/Prompt.java
feat: add cline diff to composer
> feat: add cline diff to composer

- jcommon/mcp/gateway/README.md
- jcommon/mcp/gateway/pom.xml
- jcommon/mcp/gateway/src/main/java/run/mone/supergateway/SuperGateway.java
- jcommon/mcp/gateway/src/main/java/run/mone/supergateway/config/SuperGatewayConfig.java
- jcommon/mcp/gateway/src/main/java/run/mone/supergateway/controller/SuperGatewayController.java
- jcommon/mcp/gateway/src/main/java/run/mone/supergateway/service/SseToStdioGateway.java
- jcommon/mcp/gateway/src/main/java/run/mone/supergateway/service/StdioToSseGateway.java
- jcommon/mcp/gateway/src/main/resources/application.properties
- jcommon/mcp/gateway/src/main/resources/logback.xml
java -jar target/supergateway-1.0.0.jar \
--stdio "java -jar your-mcp-server.jar"
{
"mcpServers": {
"ipinfo": {
"type": "sse",
"url": "http://localhost:8000/sse"
}
}
}
> a stdio to sse ai gateway

- jcommon/hive/pom.xml
- jcommon/hive/src/main/java/run/mone/hive/llm/ClaudeProxy.java
- jcommon/hive/src/main/java/run/mone/hive/llm/LLM.java
- jcommon/hive/src/test/java/run/mone/hive/llm/LLMTest.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/function/ComposerFunction.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/BotClient.java
> bug fix, support claude 35

- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/CodeGenerationHandler.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/FunctionalAnalysisHandler.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/biz/BotChainCall.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/prompt/CodePrompt.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/prompt/Prompt.java
Adjust the prompt to adapt to the format
> Adjust the prompt to adapt to the format

- jcommon/hive/src/main/java/run/mone/hive/llm/ClaudeProxy.java
- jcommon/hive/src/main/java/run/mone/hive/llm/LLM.java
- jcommon/hive/src/main/java/run/mone/hive/llm/LLMProvider.java
- jcommon/hive/src/test/java/run/mone/hive/llm/LLMTest.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/handler/BotClient.java
> support claude37

- jcommon/mcp/mcp-text2sql/README.md
- jcommon/mcp/mcp-text2sql/pom.xml
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/Text2SqlMcpBootstrap.java
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/config/McpSSETransportConfig.java
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/config/McpStdioTransportConfig.java
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/function/Text2SqlFunction.java
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/model/ColumnInfo.java
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/model/ForeignKey.java
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/model/IndexInfo.java
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/model/TableSchema.java
- jcommon/mcp/mcp-text2sql/src/main/java/run/mone/mcp/text2sql/server/Text2SqlMcpServer.java
- jcommon/mcp/mcp-text2sql/src/main/resources/application.properties
- jcommon/mcp/mcp-text2sql/src/test/java/run/mone/mcp/mysql/function/Text2SqlFunctionTest.java
> add mcpserver: text2sql

- jcommon/mcp/mcp-knowledge-base/README.md
- jcommon/mcp/mcp-knowledge-base/pom.xml
- jcommon/mcp/mcp-knowledge-base/src/main/java/run/mone/mcp/knowledge/base/KnowledgeBaseQueryMcpBootstrap.java
- jcommon/mcp/mcp-knowledge-base/src/main/java/run/mone/mcp/knowledge/base/config/McpSseKnowledgeBaseTransportConfig.java
- jcommon/mcp/mcp-knowledge-base/src/main/java/run/mone/mcp/knowledge/base/config/McpStudioKnowledgeBaseTransportConfig.java
- jcommon/mcp/mcp-knowledge-base/src/main/java/run/mone/mcp/knowledge/base/entity/BaseVO.java
- jcommon/mcp/mcp-knowledge-base/src/main/java/run/mone/mcp/knowledge/base/entity/VectorQueryResponse.java
- jcommon/mcp/mcp-knowledge-base/src/main/java/run/mone/mcp/knowledge/base/function/KnowledgeBaseQueryFunction.java
- jcommon/mcp/mcp-knowledge-base/src/main/java/run/mone/mcp/knowledge/base/http/HttpClient.java
- jcommon/mcp/mcp-knowledge-base/src/main/java/run/mone/mcp/knowledge/base/server/KnowledgeBaseQueryMcpServer.java
- jcommon/mcp/mcp-knowledge-base/src/main/resources/application.properties
- jcommon/mcp/pom.xml
> feat(mcp-git): Add KnowledgeBase query Sender MCP Implementation

- jcommon/mcp/mcp-hammerspoon/src/main/java/run/mone/mcp/hammerspoon/function/ChatToFunction.java
- jcommon/mcp/mcp-hammerspoon/src/main/resources/py/input.py
- jcommon/mcp/mcp-hammerspoon/src/main/resources/py/input_util.py
fix: resolved match multi window on windows system
> fix: resolved match multi window on windows system

- jcommon/hive-manager/src/main/resources/static/package.json
- jcommon/hive-manager/src/main/resources/static/src/api/agent.ts
- jcommon/hive-manager/src/main/resources/static/src/api/task.ts
- jcommon/hive-manager/src/main/resources/static/src/common/req/index.ts
- jcommon/hive-manager/src/main/resources/static/src/components/AgentDetailDrawer.vue
- jcommon/hive-manager/src/main/resources/static/src/components/CreateTaskDialog.vue
- jcommon/hive-manager/src/main/resources/static/src/components/SkillList.vue
- jcommon/hive-manager/src/main/resources/static/src/components/TaskDetailDrawer.vue
- jcommon/hive-manager/src/main/resources/static/src/main.ts
- jcommon/hive-manager/src/main/resources/static/src/router/index.ts
- jcommon/hive-manager/src/main/resources/static/src/stores/user.ts
- jcommon/hive-manager/src/main/resources/static/src/styles/common.css
- jcommon/hive-manager/src/main/resources/static/src/views/AgentList.vue
- jcommon/hive-manager/src/main/resources/static/src/views/Login.vue
- jcommon/hive-manager/src/main/resources/static/src/views/TaskList.vue
- jcommon/hive-manager/src/main/resources/static/vite.config.ts
> feat: Agent list

- jcommon/hive/src/main/java/run/mone/hive/mcp/service/RoleService.java
- jcommon/mcp/mcp-chat/src/main/resources/application.properties
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/IdeaComposerMcpBootstrap.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/config/IdeaComposerMcpConfig.java
- jcommon/mcp/mcp-idea-composer/src/main/java/run/mone/mcp/idea/composer/server/IdeaComposerMcpServer.java
- jcommon/mcp/mcp-idea-composer/src/main/resources/application.properties
- Update RoleService in hive module
- Modify application properties in mcp-chat
- Adjust application.yml in hive-manager
- Refactor IdeaComposerMcpConfig and related classes in mcp-idea-composer
- Update application properties for mcp-idea-composer
- Enhance IdeaComposerMcpServer implementation
> feat(mcp): update configuration and services across multiple modules

- jcommon/README.md
- jcommon/mcp/mcp-asr/README.md
- jcommon/mcp/mcp-asr/pom.xml
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/AsrMcpBootstrap.java
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/config/McpSseAsrTransportConfig.java
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/config/McpStudioAsrTransportConfig.java
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/function/AsrFunction.java
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/server/AsrMcpServer.java
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/service/AliAsrService.java
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/service/TencentAsrService.java
- jcommon/mcp/mcp-asr/src/main/resources/application.properties
- jcommon/mcp/mcp-tts/README.md
- jcommon/mcp/mcp-tts/pom.xml
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/TtsMcpBootstrap.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/config/McpSseTtsTransportConfig.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/config/McpStudioTtsTransportConfig.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/function/TtsFunction.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/server/TtsMcpServer.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/service/AliTtsService.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/service/PlaybackRunnable.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/service/TencentTtsService.java
- jcommon/mcp/mcp-tts/src/main/resources/application.properties
- jcommon/mcp/pom.xml
> MCP suport ASR and TTS

- jcommon/easy/src/main/java/com/xiaomi/youpin/docean/adapter/DoubleDefaultAdapter.java
- jcommon/easy/src/main/java/com/xiaomi/youpin/docean/adapter/IntegerDefaultAdapter.java
- jcommon/easy/src/main/java/com/xiaomi/youpin/docean/adapter/LongDefaultAdapter.java
- jcommon/file/src/main/java/com/xiaomi/mone/file/LogFile.java
- jcommon/file/src/main/java/com/xiaomi/mone/file/LogFile2.java
-Refactored the deserialize method in the DoubleDefault Adapter, IntegralDefault Adapter, and LongDefault Adapter classes
-Optimized the readLine method in LogFile and LogFile2 classes, added exception capture and handling
-Improved file reading process, enhanced code robustness and readability
> refactor(easy/file): Optimize log file reading logic and exception handling

- jcommon/hive-manager/src/main/java/run/mone/agentx/service/RealtimeService.java
- jcommon/hive-manager/src/main/java/run/mone/agentx/websocket/RealtimeWebSocketHandler.java
- jcommon/hive-manager/src/main/java/run/mone/agentx/websocket/WebSocketConfig.java
- 新增 RealtimeService 类，负责管理WebSocket连接和消息处理
- 新增 RealtimeWebSocketHandler 类，处理WebSocket连接的建立和关闭
- 更新 WebSocketConfig 类，注册新的实时WebSocket处理器
> feat(hive-manager): 添加实时WebSocket服务和处理器

- jcommon/hive-manager/src/main/java/run/mone/agentx/config/SecurityConfig.java
- jcommon/hive-manager/src/main/java/run/mone/agentx/service/RealtimeService.java
- jcommon/hive-manager/src/main/java/run/mone/agentx/websocket/WebSocketConfig.java
- jcommon/hive-manager/src/main/resources/static/src/views/Person.vue
- 在 SecurityConfig 中允许访问 /ws/realtime/** 路径
- 修改 RealtimeService，增加最大消息大小限制，并发送会话设置
- 更新 WebSocketConfig，注册新的 STOMP 端点
- 在 Person.vue 中添加聊天记录和消息显示功能，支持音频消息的发送和接收
> feat: 更新实时WebSocket服务和前端聊天功能

- jcommon/mcp/mcp-asr/README.md
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/function/AsrFunction.java
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/service/AliAsrService.java
- jcommon/mcp/mcp-asr/src/main/java/run/mone/mcp/asr/service/TencentAsrService.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/function/TtsFunction.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/service/AliTtsService.java
- jcommon/mcp/mcp-tts/src/main/java/run/mone/mcp/tts/service/TencentTtsService.java
> ASR，TTS support base64 

- jcommon/hive-manager/src/main/java/run/mone/agentx/config/JwtAuthenticationFilter.java
> feat: front web

- jcommon/hive-manager/src/main/resources/static/package.json
- jcommon/hive-manager/src/main/resources/static/src/components/AgentDetailDrawer.vue
- jcommon/hive-manager/src/main/resources/static/src/styles/common.css
> feat: json style

- jcommon/hive-manager/src/main/resources/static/src/components/Chat/assets/scss/MarkdownMessage.scss
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/assets/scss/highlight.scss
> feat: style

- jcommon/hive-manager/src/main/resources/static/src/components/Chat/common/result-code/index.ts
> feat: command

- jcommon/hive-manager/src/main/resources/static/src/views/Chat.vue
> feat: add conversationId

- jcommon/hive-manager/src/main/resources/static/src/views/Chat.vue
> feat: owner_id

- jcommon/hive-manager/src/main/resources/static/src/api/agent.ts
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/InstanceSelect.vue
> feat: clear history

- jcommon/hive-manager/src/main/resources/static/src/api/message.ts
- jcommon/hive-manager/src/main/resources/static/src/views/Chat.vue
> feat: mapdata

- jcommon/hive-manager/src/main/resources/static/src/api/agent.ts
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/ChatWindow.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/InstanceSelect.vue
- jcommon/hive-manager/src/main/resources/static/src/views/Chat.vue
> feat: clear

- jcommon/hive-manager/src/main/resources/static/src/api/agent.ts
- jcommon/hive-manager/src/main/resources/static/src/components/AgentDetailDrawer.vue
> feat: agent detail

- jcommon/hive-manager/src/main/resources/static/src/api/task.ts
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/messages/MarkdownMessage.vue
- jcommon/hive-manager/src/main/resources/static/src/components/CreateTaskDialog.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Header.vue
- jcommon/hive-manager/src/main/resources/static/src/components/TaskDetailDrawer.vue
- jcommon/hive-manager/src/main/resources/static/src/router/index.ts
- jcommon/hive-manager/src/main/resources/static/src/views/AgentList.vue
- jcommon/hive-manager/src/main/resources/static/src/views/TaskList.vue
> feat: task

- jcommon/hive-manager/src/main/resources/static/src/api/agent.ts
- jcommon/hive-manager/src/main/resources/static/src/api/user.ts
- jcommon/hive-manager/src/main/resources/static/src/components/AccessList.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Header.vue
- jcommon/hive-manager/src/main/resources/static/src/views/AgentList.vue
> feat: search

- jcommon/hive-manager/src/main/resources/static/src/views/AgentList.vue
> feat: path

- jcommon/hive-manager/src/main/resources/static/src/api/message.ts
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/common/result-code/index.ts
> feat: image

- jcommon/hive-manager/src/main/resources/static/src/App.vue
- jcommon/hive-manager/src/main/resources/static/src/api/toekn.ts
- jcommon/hive-manager/src/main/resources/static/src/components/BindInner.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Header.vue
- jcommon/hive-manager/src/main/resources/static/src/components/LeftComp.vue
- jcommon/hive-manager/src/main/resources/static/src/components/ThemeSwitcher.vue
- jcommon/hive-manager/src/main/resources/static/src/components/TokenDialog.vue
- jcommon/hive-manager/src/main/resources/static/src/styles/theme/variables.scss
- jcommon/hive-manager/src/main/resources/static/src/views/AgentList.vue
- jcommon/hive-manager/src/main/resources/static/src/views/TaskList.vue
> feat: token

- jcommon/hive-manager/src/main/resources/static/src/components/Header.vue
- jcommon/hive-manager/src/main/resources/static/src/components/ThemeSwitcher.vue
- jcommon/hive-manager/src/main/resources/static/src/components/TokenDialog.vue
- jcommon/hive-manager/src/main/resources/static/src/views/AgentList.vue
- jcommon/hive-manager/src/main/resources/static/src/views/TaskList.vue
> feat: header

- jcommon/hive-manager/src/main/resources/static/src/api/agent.ts
- jcommon/hive-manager/src/main/resources/static/src/api/message.ts
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/InstanceSelect.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/UserInput.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/components/image-upload/index.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/messages/MediaMessage.vue
- jcommon/hive-manager/src/main/resources/static/src/components/InvokeHistory.vue
- jcommon/hive-manager/src/main/resources/static/src/plugins/markdown-it-mcp.ts
- jcommon/hive-manager/src/main/resources/static/src/plugins/simple-html-parser.ts
- jcommon/hive-manager/src/main/resources/static/src/stores/chat-context.ts
- jcommon/hive-manager/src/main/resources/static/src/styles/markdown-mcp.scss
- jcommon/hive-manager/src/main/resources/static/src/utils/getQuery.ts
- jcommon/hive-manager/src/main/resources/static/src/views/AgentList.vue
- jcommon/hive-manager/src/main/resources/static/src/views/Chat.vue
> feat: download file

- jcommon/hive/src/main/java/run/mone/hive/llm/ClaudeProxy.java
- jcommon/hive/src/test/java/run/mone/hive/llm/LLMTest.java
- jcommon/hive/src/test/java/run/mone/hive/prompt/PromptTest.java
[test(hive): add unit tests for Prompt and LLM classes
> [test(hive): add unit tests for Prompt and LLM classes

- jcommon/hive-manager/src/main/resources/application.yml
- jcommon/hive/src/main/java/run/mone/hive/prompt/MonerSystemPrompt.java
- jcommon/hive/src/main/java/run/mone/hive/roles/tool/ExecuteCommandTool.java
update ExecuteCommandTool, usage prompt
> update ExecuteCommandTool, usage prompt

- jcommon/hive-manager/src/main/resources/static/src/components/Chat/ChatWindow.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/MessageList.vue
- jcommon/hive-manager/src/main/resources/static/src/components/Chat/common/result-code/index.ts
- jcommon/hive-manager/src/main/resources/static/src/stores/edit.ts
- jcommon/hive-manager/src/main/resources/static/src/views/Chat.vue
> feat: follow

- jcommon/mcp/mcp-feishu/pom.xml
- jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/function/FeishuDocFunction.java
- jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/model/FileInfo.java
- jcommon/mcp/mcp-feishu/src/main/java/run/mone/mcp/feishu/service/FeishuDocService.java
- jcommon/mcp/mcp-feishu/src/test/java/run/mone/mcp/feishu/function/FeishuDocFunctionTest.java
feat: refactor MCP feishu module and migrate to new SDK
> feat: refactor MCP feishu module and migrate to new SDK

- jcommon/mcp/mcp-vue3/README.md
- jcommon/mcp/mcp-vue3/pom.xml
- jcommon/mcp/mcp-vue3/src/main/java/run/mone/mcp/vue3/Vue3McpBootstrap.java
- jcommon/mcp/mcp-vue3/src/main/java/run/mone/mcp/vue3/config/AgentConfig.java
- jcommon/mcp/mcp-vue3/src/main/java/run/mone/mcp/vue3/function/Vue3TemplateFunction.java
- jcommon/mcp/mcp-vue3/src/main/java/run/mone/mcp/vue3/service/Vue3TemplateService.java
- jcommon/mcp/mcp-vue3/src/main/resources/application.properties
- jcommon/mcp/mcp-vue3/src/test/java/run/mone/mcp/vue3/function/Vue3TemplateFunctionTest.java
- jcommon/mcp/pom.xml
> feat: 创建vue3 tenplate mcp
